language: go

go:
  - 1.8
  - tip

sudo: required

env:
  global:
    - ORACLE_HOME=/usr/lib/oracle/12.1/client64
    - ORACLE_SID=XE
    - ORACLE_COOKIE=ic_linuxx8664
    - PKG_CONFIG_PATH=~/.pkgconfig
before_install:
  - mkdir $PKG_CONFIG_PATH
  - sudo apt-get --no-install-recommends -qq install alien bc libaio1 unzip
  - wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz'
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz
  - ORACLE_FILE=instantclient/121020/instantclient-basic-linux.x64-12.1.0.2.0.zip .travis/oracle/download.sh
  - unzip .travis/oracle/instantclient-basic-linux.x64-12.1.0.2.0.zip
  - ORACLE_FILE=instantclient/121020/instantclient-sdk-linux.x64-12.1.0.2.0.zip .travis/oracle/download.sh
  - unzip .travis/oracle/instantclient-sdk-linux.x64-12.1.0.2.0.zip
  - export LD_LIBRARY_PATH="${ORACLE_HOME}/lib"
  - echo $PATH
  - echo $LD_LIBRARY_PATH
  - >
    { echo "Name: oci8"; echo "Description: Oracle Call Interface"; echo "Version: 12.1";
      echo "Cflags: -I$ORACLE_HOME/sdk/include";
      echo "Libs: -L$ORACLE_HOME -Wl,-rpath,$ORACLE_HOME -lclntsh";
    } | tee ~/.pkgconfig/oci8.pc

script:
  - make style
  - make vet
  - make test
  - make build

matrix:
  allow_failures:
    - go: tip
